### ISSUE TITLE
Robotic/odd audio with scarlett solo 3rd gen

### ISSUE THREAD

**Issue by SriRamanujam** [geoffreybennett/scarlett-gen2#28]
Hi,

I'm encountering a consistently odd problem. Any audio recorded through my mic sounds robotic/oddly sampled, almost as if all of the default settings were completely incorrect. I'm not really sure how to troubleshoot this.

Misc notes:

* I'm on Fedora 41, though this issue was present on Fedora 40 as well. Kernel 6.11.5
* The same settings work without issue on Windows, so it's not a hardware configuration issue as far as I can tell

I've uploaded a representative audio sample. This is all just me talking normally into the mic, but the recordings are consistently messed up. It's a flac, you'll need to ungzip it because Github doesn't let you upload raw audio files. 

[Recording 14.flac.gz](https://github.com/user-attachments/files/17612325/Recording.14.flac.gz)

**Comment by geoffreybennett** [comment]
Hi @SriRamanujam,

Yeah, that's really messed up!

![Screenshot from 2024-11-05 22-55-22](https://github.com/user-attachments/assets/bd05bad5-97de-4cb3-9735-9b6d4ef6795b)

I don't what the problem is, but it is unrelated to the scarlett-gen2 driver, which has nothing to do with the actual recording/playback of audio (please see https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md), but let's see if we can figure it out...

Can you provide more details about your setup please? I only use Fedora as my desktop, and I can't reproduce your issue. I brought home my work laptop this evening to test, as the audio config on there would be closer to Fedora defaults. It was running Fedora 40, and it can record no problems from my 3rd Gen Solo. I upgraded it to Fedora 41, kernel 6.11.5 same as you, still no problems recording.

How are you recording? Have you made any sound-related configuration changes? Can you reproduce the problem using a Fedora Live CD?

Thanks,
Geoffrey.

**Comment by SriRamanujam** [comment]
So, some good/bad news - I thought I'd give the gui a try, and it immediately prompted for a firmware update. So I took it, and that fixed the issue! 

Failing firmware: 1535
Working firmware: 1605

I guess it was just that easy, huh. I'll close this out. Thanks for taking a look!

**Comment by geoffreybennett** [comment]
Wow, thanks for letting me know! I'll keep that one in mind; I didn't realise this could be an issue.
