### ISSUE TITLE
No sound on Linux 6.12.1. Clarett+ 2Pre

### ISSUE THREAD

**Issue by perfect7gentleman** [geoffreybennett/scarlett-gen2#29]
It is detect, but there is no `Focusrite Clarett+ Mixer Driver enabled (pid=0x820a); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues`.
It works fine on Linux 6.11.8.
```
 ~ $ lsusb | grep -i focus
Bus 002 Device 005: ID 1235:820a Focusrite-Novation Clarett+ 2Pre
```
```
 ~ $ dmesg | grep -i focus
[    3.749901] usb 2-10: Manufacturer: Focusrite
``` 
```
 ~ $ dmesg | grep -i clar
[    3.749900] usb 2-10: Product: Clarett+ 2Pre
```
There is no C2Pre in /proc/asound.
```
 ~ $ cat /proc/asound/cards 
--- no soundcards ---
```
```
 ~ $ zcat /proc/config.gz | grep -i usb_aud 
CONFIG_SND_USB_AUDIO=m
# CONFIG_SND_USB_AUDIO_MIDI_V2 is not set
```
I've tried to force device detection by 
```
 ~ $ cat /etc/modprobe.d/Clarett+2Pre.conf 
options snd_usb_audio vid=0x1235 pid=0x820a device_setup=1
```
but it did not help.

**Comment by perfect7gentleman** [comment]
Solved

**Comment by geoffreybennett** [comment]
Oh good! There weren't any changes from 6.11.8 to 6.12.1 in the scarlett2 driver so I was going to say the problem would either be in the generic USB audio driver or something in your local setup. For anyone coming across this in the future, what was the problem/what did you do to fix it?

Also FYI `device_setup=1` does nothing for this driver since this commit which went into Linux 6.7: https://lore.kernel.org/all/89600a35b40307f2766578ad1ca2f21801286b58.1694705811.git.g@b4.vu changing the driver from being disabled by default to being enabled by default.

**Comment by perfect7gentleman** [comment]
Gentoo. Installing kernel modules went wrong, so there was no modules at all. Fix kernel installation script and voilà.
